---
title: I'm receiving an `access_token` error when trying to run queries in the IDE.
description: "Reauthenticate warehouse when seeing `access_token` error"
sidebar_label: '`access_token` error in the IDE'
id: access_token_error

---

If you're seeing the below error when you try to run queries in the IDE, have no fear - we'll do our best to get you unstuck with the following steps! 

 `access_token`

In order to resolve the issue, you'll want to:

1. Go to you Profile (upper right corner of dbt Cloud)
2. Click on the correct warehouse connection under "Credentials"
3. Click "Connect Snowflake Account" green button in the "Development Credentials" section. This drives you through reauthentication through the SSO flow. 

If you've tried the step above and are still experiencing this behavior - reach out to the Support team at support@getdbt.com and we'll be happy to help!


